"""init_schema

Revision ID: 6a4f835d9941
Revises: 
Create Date: 2026-05-05 06:52:34.604653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4f835d9941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_status'), 'batch', ['status'], unique=False)
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_domain'), 'domain', ['domain'], unique=True)
    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('plan_type', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('id_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_json_path', sa.String(length=512), nullable=False),
    sa.Column('cpa_synced', sa.Boolean(), nullable=False),
    sa.Column('cpa_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpa_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_batch_id'), 'account', ['batch_id'], unique=False)
    op.create_index(op.f('ix_account_cpa_synced'), 'account', ['cpa_synced'], unique=False)
    op.create_index(op.f('ix_account_created_at'), 'account', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_table('pending_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('error_kind', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_via', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_pending_email')
    )
    op.create_index(op.f('ix_pending_account_batch_id'), 'pending_account', ['batch_id'], unique=False)
    op.create_index(op.f('ix_pending_account_email'), 'pending_account', ['email'], unique=False)
    op.create_index(op.f('ix_pending_account_error_kind'), 'pending_account', ['error_kind'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_token_hash'), 'session', ['token_hash'], unique=True)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_token_hash'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_pending_account_error_kind'), table_name='pending_account')
    op.drop_index(op.f('ix_pending_account_email'), table_name='pending_account')
    op.drop_index(op.f('ix_pending_account_batch_id'), table_name='pending_account')
    op.drop_table('pending_account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_index(op.f('ix_account_created_at'), table_name='account')
    op.drop_index(op.f('ix_account_cpa_synced'), table_name='account')
    op.drop_index(op.f('ix_account_batch_id'), table_name='account')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_index(op.f('ix_domain_domain'), table_name='domain')
    op.drop_table('domain')
    op.drop_index(op.f('ix_batch_status'), table_name='batch')
    op.drop_table('batch')
    # ### end Alembic commands ###
